services:
  - type: web
    name: savannah-elimu-connect
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 4 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: savannah-elimu-db
          property: connectionString
      - key: GOOGLE_SEARCH_API_KEY
        sync: false
      - key: GOOGLE_SEARCH_ENGINE_ID
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: savannah-elimu-db
    plan: free
    ipAllowList: [] 